apiVersion: v1
kind: Secret
metadata:
  name: auth-secret
type: Opaque
stringData:
  ALGORITHM: HS256
  SECRET_KEY: EZL4XQNanvSlLucjWugs5AYL80FCJxSaDfnibNMBRp0EiW4x7LYd_Z9BKa0x355FJnjdo2xXm-w_MC32fMev2w
  EMAIL_FROM: youremail@gmail.com
  APP_PASSWORD: app-pass-wor-d
