apiVersion: apps/v1
kind: Deployment
metadata:
  name: converter-deployment
  labels:
    app: converter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: converter
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 8
  template:
    metadata:
      labels:
        app: converter
    spec:
      containers:
        - name: converter
          image: pritamsarkar123/vtm3_converter_kube_2024:latest
          env:
            - name: RABBITMQ_HOST
              valueFrom:
                configMapKeyRef:
                  name: rabbitmq-configmap
                  key: rabbitmq-url

            - name: RABBITMQ_PORT
              valueFrom:
                configMapKeyRef:
                  name: rabbitmq-configmap
                  key: rabbitmq-port
            
            - name: RABBITMQ_USERNAME
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: rabbitmq-username

            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: rabbitmq-password

            - name: MONGO_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: mongo-user

            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: mongo-password

            - name: MONGO_HOST
              valueFrom:
                configMapKeyRef:
                  name: mongo-configmap
                  key: mongo-url

            - name: MONGO_PORT
              valueFrom:
                configMapKeyRef:
                  name: mongo-configmap
                  key: mongo-port
          envFrom:
            - configMapRef:
                name: converter-configmap
            - secretRef:
                name: converter-secret


