apiVersion: apps/v1
kind: Deployment
metadata:
  name: notifier-deployment
  labels:
    app: notifier
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notifier
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 8
  template:
    metadata:
      labels:
        app: notifier
    spec:
      containers:
        - name: notifier
          image: pritamsarkar123/vtm3_notifier_kube_2024:latest
          env:
            - name: RABBITMQ_HOST
              valueFrom:
                configMapKeyRef:
                  name: rabbitmq-configmap
                  key: rabbitmq-url

            - name: RABBITMQ_PORT
              valueFrom:
                configMapKeyRef:
                  name: rabbitmq-configmap
                  key: rabbitmq-port

            - name: RABBITMQ_USERNAME
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: rabbitmq-username

            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: rabbitmq-password

          envFrom:
            - configMapRef:
                name: notifier-configmap
            - secretRef:
                name: notifier-secret




